### ISSUE TITLE
Can't find devices

### ISSUE THREAD

**Issue by Eric9453** [georgezhao2010/apple_airplayer#10]
我沒有蘋果設備，但利用Hassio中的Airsonos和Aircast Add-ons把小愛pro及nest mini轉成為Airplay設備
安裝您的這個套件下去後，無法找到這兩個透過模擬後的Airplay設備

請問有解嗎？謝謝

**Comment by georgezhao2010** [comment]
该集成可能无法支持所有的第三方的AirPlay兼容设备，如果无法发现，可能是不兼容的情况。

**Comment by Eric9453** [comment]
原来如此,，不得不说这是个好专案
谢谢您的持续产出
