### ISSUE TITLE
Home assistant restarts when TTS is used

### ISSUE THREAD

**Issue by Fannangir** [georgezhao2010/apple_airplayer#21]
Hi,
In the last version of HA, OS 6.6, Supervisor 2021.10.8, Core 2021.11.5, HA server restarts if TTS is used.
miniaudio is not installed by default in this version.
Tried to install it, still same behavior.

Is there any solution to make the integration work?

Thanks.

**Comment by Dodoooh** [comment]
same problem here. 

already tried many things that have previously helped as a fix but without success

**Comment by bfreeTax** [comment]
Still happens on 2021.12 RC, logs are not very helpful:

`today at 20:57:01[finish] process exit code 256
today at 20:57:01[finish] process received signal 4
today at 20:57:01[cont-finish.d] executing container finish scripts...
today at 20:57:01[cont-finish.d] done.
today at 20:57:01[s6-finish] waiting for services.
today at 20:57:02[s6-finish] sending all processes the TERM signal.
today at 20:57:05[s6-finish] sending all processes the KILL signal and exiting.`

**Comment by garanda21** [comment]
Still happens on 2021.12 RC, logs are not very helpful:

`today at 20:57:01[finish] process exit code 256
today at 20:57:01[finish] process received signal 4
today at 20:57:01[cont-finish.d] executing container finish scripts...
today at 20:57:01[cont-finish.d] done.
today at 20:57:01[s6-finish] waiting for services.
today at 20:57:02[s6-finish] sending all processes the TERM signal.
today at 20:57:05[s6-finish] sending all processes the KILL signal and exiting.`

**Comment by georgezhao2010** [comment]
I guess you used HASSOS and didn't run the commands in the HA docker.

1. In HASSOS, type `login` and enter, type `root` and enter.
2. Run `docker exec -it homeassistant /bin/bash` into your HA docker.
3. Run the following commands
```
apk update
apk add build-base
pip3 uninstall --yes miniaudio
pip3 install miniaudio
```

**Comment by Fannangir** [comment]
Tried it as well, no luck.
Found the following:
https://github.com/postlund/hass-atv-beta
Works like a charm out of the box, including artwork, control and TTS.

**Comment by Fannangir** [comment]
@georgezhao2010 , you are right, it solves the issue.
I have missed the restart following the reinstallation of miniaudio.
Thanks for the tip.
