### ISSUE TITLE
How I can contact you by email?

### ISSUE THREAD

**Issue by Neustradamus** [georgezhao2010/apple_airplayer#22]
@georgezhao2010: How I can contact you by email?

Can I have your email address?

You can remove this ticket after sending the reply ^^

Thanks in advance.

**Comment by georgezhao2010** [comment]
> @georgezhao2010: How I can contact you by email?
> 
> Can I have your email address?
> 
> You can remove this ticket after sending the reply ^^
> 
> Thanks in advance.

georgezhao75@gmail.com

**Comment by Neustradamus** [comment]
@georgezhao2010: Thanks, I will send you an email soon!
You can remove this ticket (feature at right of this issue)

**Comment by Neustradamus** [comment]
@georgezhao2010: Have you received my email?
Thanks in advance.
