### ISSUE TITLE
It does not work while run tts, no voice

### ISSUE THREAD

**Issue by tomcheng1111** [georgezhao2010/apple_airplayer#5]
It gets 2 error logs. 

`
This error originated from a custom integration.

Logger: custom_components.apple_airplayer.device_manager
Source: custom_components/apple_airplayer/device_manager.py:105
Integration: Apple AirPlayer (documentation, issues)
First occurred: 10:28:32 PM (1 occurrences)
Last logged: 10:28:32 PM

Exception raised in async_stream_file, RTSP/1.0 method SETUP failed with code 500: Internal Server Error
`

`
Logger: gtts.lang
Source: /usr/local/lib/python3.9/site-packages/gtts/lang.py:94
First occurred: 10:28:30 PM (1 occurrences)
Last logged: 10:28:30 PM

'zh-tw' has been deprecated, falling back to 'zh-TW'. This fallback will be removed in a future version.
`
`
System Health

version: core-2021.8.6
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
user: root
virtualenv: false
python_version: 3.9.6
os_name: Linux
os_version: 5.10.17-v8
arch: aarch64
timezone: Asia/Taipei

GitHub API: ok
Github API Calls Remaining: 4935
Installed Version: 1.13.2
Stage: running
Available Repositories: 845
Installed Repositories: 8

logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

host_os: Home Assistant OS 6.2
update_channel: stable
supervisor_version: supervisor-2021.06.8
docker_version: 20.10.6
disk_total: 56.4 GB
disk_used: 14.8 GB
healthy: true
supported: true
board: rpi4-64
supervisor_api: ok
version_api: ok
installed_addons: Home Assistant Google Drive Backup (0.104.3), File editor (5.3.3), Node-RED (10.0.0), Duck DNS (1.12.5), Mosquitto broker (6.0.1), FTP (4.2.0), SSH & Web Terminal (9.0.1), SQLite Web (3.1.0), Samba NAS (9.3.0-nas8)

dashboards: 1
resources: 1
views: 3
mode: storage

logged_in: true
can_reach_micloud_server: ok
accounts_count: 1
account_devices_count: 21
added_devices: 9
`

**Comment by georgezhao2010** [comment]
> It gets 2 error logs.
> 
> `
> This error originated from a custom integration.
> 
> Logger: custom_components.apple_airplayer.device_manager
> Source: custom_components/apple_airplayer/device_manager.py:105
> Integration: Apple AirPlayer (documentation, issues)
> First occurred: 10:28:32 PM (1 occurrences)
> Last logged: 10:28:32 PM
> 
> Exception raised in async_stream_file, RTSP/1.0 method SETUP failed with code 500: Internal Server Error
> ...

What's your playback device?  Failure always or sometimes?

**Comment by tomcheng1111** [comment]
I want to play tts on homepod mini.
Failures always reported.
pyatv version is 0.8.2 

If need information anymore, please reply me.

> What's your playback device? Failure always or sometimes? and are you upgraded pyatv in supervisor-2021.06.8? second issue may an issue in google tts component.

**Comment by georgezhao2010** [comment]
In HomePod settings, need authentication or someting?

**Comment by tomcheng1111** [comment]
> In HomePod settings, need authentication or someting?

Fork this integration, no necessary.
